### ISSUE TITLE
Need a method which converts User object into JSON format

### ISSUE THREAD

**Issue by Shahrier-Al-Tanzim** [Talha76/TrafficRecordManagementSystem#3]
I can't flash the user object into the ejs file, the compiler saying I need to parse this a JSON 
so whenever I make ```let user = new User ({mail : _mail})``` I need to make that user into JSON

I guess I need a js object like ``` let newUser =[]``` which can be flashed

**Comment by Talha76** [comment]
This issue is raised due to circular reference. This mainly occured because the User class has Vehicle class, and the Vehicle class has user class, making it a circular relationship. This is a code smell.

**Comment by Talha76** [comment]
I will fix it soon.

**Comment by Talha76** [comment]
Fixed in this commit [dcc08f1cb745557c9cf0de3957c69e42fc313cea](https://github.com/Talha76/TrafficRecordManagementSystem/commit/dcc08f1cb745557c9cf0de3957c69e42fc313cea).
